name: build-test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CGO_ENABLED: "1"

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        run: |
          if test -z "$(gofmt -l .)"; then
            echo "Congrats! There is nothing to fix."
          else
            echo "The following lines should be fixed."
            gofmt -s -d .
            exit 1
          fi

      - name: Build Tracee
        run: make build-docker
  
  test:
    runs-on: ubuntu-20.04

    env:
      CGO_ENABLED: "1"

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt install -y bison build-essential cmake flex git libedit-dev \
              llvm libllvm10 llvm-dev libclang-dev  python zlib1g-dev libelf-dev \
              libtinfo5 libfl-dev
          git submodule update --init
          sudo make bpf

      - name: Run Tests
        run: make test
      